insert into book (id, brief, publish_year, author) values (1, 'pellentesque eget nunc donec quis orci eget', 1968, 'Linda Hughes');
insert into book (id, brief, publish_year, author) values (2, 'amet erat nulla tempus vivamus', 1904, 'Tammy Brooks');
insert into book (id, brief, publish_year, author) values (3, 'porta volutpat quam pede lobortis', 1973, 'Billy Davis');
insert into book (id, brief, publish_year, author) values (4, 'est congue elementum in hac habitasse', 1959, 'Diane Carter');
insert into book (id, brief, publish_year, author) values (5, 'ante ipsum primis in faucibus', 1949, 'Timothy Jordan');
insert into book (id, brief, publish_year, author) values (6, 'turpis adipiscing lorem vitae mattis nibh ligula', 1934, 'Carolyn Ramos');
insert into book (id, brief, publish_year, author) values (7, 'vestibulum sagittis sapien', 1976, 'Paul Ramirez');
insert into book (id, brief, publish_year, author) values (8, 'id nisl venenatis lacinia', 2014, 'Stephanie Lawson');
insert into book (id, brief, publish_year, author) values (9, 'ultricies eu nibh quisque id justo', 1941, 'Michelle Butler');
insert into book (id, brief, publish_year, author) values (10, 'ac est lacinia', 1930, 'Anne Ray');
insert into book (id, brief, publish_year, author) values (11, 'elementum pellentesque quisque porta volutpat', 1910, 'Nicholas Reyes');
insert into book (id, brief, publish_year, author) values (12, 'vitae quam', 1980, 'Donald Matthews');
insert into book (id, brief, publish_year, author) values (13, 'in magna bibendum imperdiet nullam orci', 1901, 'Mary Black');
insert into book (id, brief, publish_year, author) values (14, 'sociis natoque penatibus', 1981, 'Brian West');
insert into book (id, brief, publish_year, author) values (15, 'faucibus orci luctus et ultrices', 1912, 'Joyce Carroll');
insert into book (id, brief, publish_year, author) values (16, 'libero convallis eget eleifend luctus', 1951, 'Paula Morales');
insert into book (id, brief, publish_year, author) values (17, 'morbi ut odio cras mi', 1958, 'Helen Lewis');
insert into book (id, brief, publish_year, author) values (18, 'eu nibh quisque id justo sit', 1908, 'Ernest Alvarez');
insert into book (id, brief, publish_year, author) values (19, 'posuere cubilia curae donec', 1939, 'Annie Romero');
insert into book (id, brief, publish_year, author) values (20, 'vestibulum ante ipsum primis in faucibus', 1988, 'David Austin');
insert into book (id, brief, publish_year, author) values (21, 'id ornare imperdiet sapien urna pretium nisl', 1995, 'Marilyn Baker');
insert into book (id, brief, publish_year, author) values (22, 'dictumst aliquam augue', 1922, 'Chris Harrison');
insert into book (id, brief, publish_year, author) values (23, 'ut dolor morbi vel lectus', 2012, 'John Watkins');
insert into book (id, brief, publish_year, author) values (24, 'justo sit amet sapien dignissim', 2003, 'Roger Lynch');
insert into book (id, brief, publish_year, author) values (25, 'posuere cubilia curae mauris viverra diam', 1916, 'Annie Jordan');
insert into book (id, brief, publish_year, author) values (26, 'in hac', 1933, 'Roy Mendoza');
insert into book (id, brief, publish_year, author) values (27, 'vel accumsan tellus nisi', 2006, 'Brandon Willis');
insert into book (id, brief, publish_year, author) values (28, 'odio donec', 1944, 'Keith Hernandez');
insert into book (id, brief, publish_year, author) values (29, 'donec diam neque vestibulum eget vulputate ut', 1964, 'Evelyn Allen');
insert into book (id, brief, publish_year, author) values (30, 'natoque penatibus et magnis dis', 1970, 'Anthony Rose');
insert into book (id, brief, publish_year, author) values (31, 'in sagittis dui vel nisl', 1972, 'Janice Gutierrez');
insert into book (id, brief, publish_year, author) values (32, 'eget nunc donec', 1920, 'Brandon Wilson');
insert into book (id, brief, publish_year, author) values (33, 'eget eros', 1976, 'Virginia Little');
insert into book (id, brief, publish_year, author) values (34, 'quisque ut erat curabitur gravida nisi at', 2016, 'Adam Gilbert');
insert into book (id, brief, publish_year, author) values (35, 'vestibulum vestibulum', 1904, 'Peter Meyer');
insert into book (id, brief, publish_year, author) values (36, 'nisl ut volutpat sapien arcu sed augue', 1928, 'Matthew Martin');
insert into book (id, brief, publish_year, author) values (37, 'aliquam sit amet diam in magna', 1961, 'Anthony Smith');
insert into book (id, brief, publish_year, author) values (38, 'morbi ut', 1968, 'Rachel Fox');
insert into book (id, brief, publish_year, author) values (39, 'nisl duis ac nibh fusce lacus purus', 1977, 'Arthur Lawrence');
insert into book (id, brief, publish_year, author) values (40, 'turpis nec euismod scelerisque', 1940, 'Anthony Stevens');
insert into book (id, brief, publish_year, author) values (41, 'donec semper sapien a libero', 1910, 'Alice Welch');
insert into book (id, brief, publish_year, author) values (42, 'in purus eu', 1942, 'Jimmy Hunter');
insert into book (id, brief, publish_year, author) values (43, 'bibendum morbi', 1972, 'Joyce Owens');
insert into book (id, brief, publish_year, author) values (44, 'ultrices aliquet', 2003, 'Norma White');
insert into book (id, brief, publish_year, author) values (45, 'platea dictumst maecenas ut massa quis augue', 1951, 'Lawrence Cooper');
insert into book (id, brief, publish_year, author) values (46, 'cursus id turpis integer aliquet massa', 1979, 'Rachel Wagner');
insert into book (id, brief, publish_year, author) values (47, 'natoque penatibus et magnis', 2010, 'Walter Ramos');
insert into book (id, brief, publish_year, author) values (48, 'ante vestibulum', 1920, 'Emily Gutierrez');
insert into book (id, brief, publish_year, author) values (49, 'nunc commodo placerat praesent blandit', 1917, 'Kimberly Payne');
insert into book (id, brief, publish_year, author) values (50, 'vivamus vel nulla eget eros', 1943, 'Denise Gonzales');
